### PR TITLE
SFML 2.3 update, D-Side

### PR DESCRIPTION
**Pull request by aubade**
This is the companion PR to https://github.com/Jebbs/DSFMLC/pull/6

I've got most of the new methods and classes wrapped in DSFML; I've tried to keep approximately to the current coding and documentation-commenting style. 

At the moment this probably isn't ready for merging either; I haven't yet made a pass to see things I've missed, and I've only tested to see that it didn't break what was already there.

### CODE REVIEW

**Comment by Jebbs** [comment]
Thanks for getting going on this. It's a big thing to work on. 

I haven't looked over much yet, but I have some thoughts:
1. It might be a good idea to merge this into a separate 2.3 branch before direct merge into master, like what I was doing for DSFMLC. 
2. Don't worry about failing stuff on Appveyor. Looks like something is up with the script is wonky.
3. How much time are you dedicating to this right now? I'm only enrolled in one class this term so I was going to put a bunch of time into DSFML before GSoC starts (if I get accepted), and that includes getting 2.3 out and 2.4 started.

I'll be able to give more feedback soon and we can hopefully coordinate work on this together.

**Comment by aubade** [comment]
1. A separate branch would probably be a good idea! There was already one to file against on DSFMLC, but afaict github doesrn't let you request a new branch start.
2. Yeah; travis-ci was easy to figure out, but I'm not sure exactly what the appveyor errors mean; it seems to compile and (mostly) run on windows just fine.
3. What I've filed here was about two days of pretty solid effort; I've let this sit since the PR, since everything I've poked at seems to work, but I'd be happy to dedicate some more time to it as needed.

**Comment by aubade** [comment]
Just to clarify the 'mostly'--The issue I've run into on windows is that the joystick names don't look right. I've got three hooked up atm; Two have the first letters of their names wrong, one looks like a series of hex codes. I've gotta try writing some C++ code to test to see if it's an issue there.

**Comment by Jebbs** [comment]
Ok, I can start a separate branch for this. The appveyor errors look like they're implib related so I can look into that. The last question I asked was mainly geared at seeing how much we needed to coordinate, but it sounds like you took care of everything as far as updating to 2.3 goes? Aside from the issues you mentioned, that is.

**Comment by aubade** [comment]
I'm pretty sure so; I updated everything mentioned in the changelog and API reference, and I've already got my personal project using this code without issue.

**Comment by Jebbs** [comment]
So, one thing I saw is that when I started the work on the DSFMLC 2.3 branch, I didn't everything set up all the way or something. All of the implib stuff is missing from that branch and that's why you are getting the appveyor errors for 32 bit dmd. If you want to copy all of it from the master repository and just pop it in, it should be good to go. There is a .bat file in the top level of the repo, and the rest is in extlibs.

I've started a 2.3 branch, so if you want to open up a PR for that I'll merge it right away. I can then start doing the non SFML update parts I was planning before the release.

**Comment by aubade** [comment]
Alrighty! I tossed the implib stuff up on the DSFMLC branch. I didn't think to do it before issuing the new PR, so we still will have an appveyor fail or two, unfortunately.

**Comment by Jebbs** [comment]
I think I'll close this one since the same stuff has merged into the 2.3 branch and I'll be doing more work there. I can merge that branch into master once I'm finished.

**Pull request closed without merging**
