### PR TITLE
Convert Clock, etc, to use core.time.Duration

### PR DESCRIPTION
**Pull request by luke5542**
I have removed `dsfml.system.time` and converted all related code to using `core.time.Duration`. Similarly, I have removed `dsfml.system.clock`'s dependency on DSFMLC and written it to use `core.time.MonoTime` instead.

This is in an attempt to move forward with #139, #180, #179 (though it is still a class instead of a struct).

Feedback and discussion is most welcome!

### CODE REVIEW

**Comment by luke5542** [comment]
Hmm... well that's upsetting... Now time to see what part of MonoTime was added with 2.067, or we could up the compiler support to 2.068 and 2.067?

**Comment by Jebbs** [comment]
I'm not at a computer, do you want to do a quick pr for a few compiler version additions to the travis yml file? Maybe add some gdc and ldc compilers too? I still need to get Appveyor put together, so don't worry about that one yet.

I have a couple of comments, but it's all minor stuff.

By the way, I have mixed feelings about this, but I think it's the right direction. :P

**Comment by Jebbs** [comment]
Oh, whoops. I completely missed the point of what you even said.

Is there something else we could use besides MonoTime? Changing the required compiler version to be 2.067 would leave gcc out of the picture. It's currently at 2.066.1. :/

**Comment by Jebbs** [comment]
> Now time to see what part of MonoTime was added with 2.067

All of it, actually. It didn't exist previously. MonoTime replaced TickDuration, which is now deprecated.

We could always do my previous suggestion for the time being, which is to have a single static sfClock instance and use that as our monotonic clock? Unless you have a plan.

**Comment by luke5542** [comment]
Hmm... I suppose that could work. We could also add a version flag to select between TickDuration and MonoTime, for the compilers that are a bit behind.

What is the source of your mixed feelings? Is it an efficiency concern? If so, I'll admit I'm not certain what the difference is between the two, but with this being done in D it does eliminate the extra calls/redirects involved with the pointer to the DSFMLC object.

**Comment by luke5542** [comment]
Okay, @Jebbs, what do you think now? It could probably be a bit cleaner, but I think that's likely only possible when we no longer have to support TickDuration.

**Comment by Jebbs** [comment]
I would have suggested you do something similar if I had realized that was all it would take. 

And I have mixed feelings because one of my original visions (or hopes, really) for DSFML was for C++ people to be able to easily translate their projects into D, and it almost feels like a lot of work that does basically the same thing. Removing Time shouldn't be too bad, and Duration is probably more useful, so again, I think this is probably a good idea. I'm also not worried about performance at all with this. It should be comparable or even faster as you said.

**Comment by Jebbs** [comment]
Wrote a couple of notes, but like I said, minor stuff. 

Thanks for doing this, by the way!

**Comment by luke5542** [comment]
Thanks for the comments! I've made two changes based on your suggestions.

I do see what you mean about making it easier for people to translate their projects. For the most part I agree that it's a nice thing to stay as close to the C++ version as possible, but I think the similarity is really only useful for allowing people who are already familiar with SFML to quickly get started with DSFML.

No problem! I had been wanting to make this change for a while, as one of the projects I was working on had an unnecessary dependency on DSFML due to the usage of Time rather than Duration, which would have been easier to isolate from the larger project had DSFML used Duration instead.

**Pull request merged**
