### PR TITLE
fix/improve tests

### PR DESCRIPTION
**Pull request by MartinNowak**
- load correct sound files
- make tests non-interactive
- avoid sudo to use docker on Travis-CI

### CODE REVIEW

**Comment by MartinNowak** [comment]
Seems to crash while loading a texture https://github.com/Jebbs/DSFML/blob/f03819f9bcb846f67db13cbde49fd1f32555992e/src/dsfml/system/inputstream.d#L185. Does that need an OpenGL context?

**Comment by Jebbs** [comment]
And this is what I get for not having any updated information anywhere...

All my recent work has been going into the 2.1-rc branch. It's actually basically ready for a release, I'm just finishing up tutorials. The unit tests make a bit more sense now, and if you're actually using DSFML for something I hope you'll find it much better. Hopefully this won't cause too much trouble.

Looks like I also have a bit more to learn about Travis CI!

**Comment by MartinNowak** [comment]
I rebased the PR, let's see whether it works.

**Comment by Jebbs** [comment]
Thanks a bunch for this!

It doesn't pass, but I can see why:
+ I changed the backend name from DSFML-C to DSFMLC, so the names that use DSFML-C should be updated, or at least the git clone name should.
+ I used ```${DMD} build.d``` and ```./build -unittest``` instead of ```rdmd build -unittest``` because gdc and ldc on Travis CI don't support rdmd.

I also had a couple of thoughts. Why install DSFMLC to a separate directory instead of the default? Is it better to do that and export the paths? You probably know better than me, but so I'm curious. Also, some of the tests do currently require user input(some input/event ones I think). Is Travis CI going to freak out if it never finishes?

**Comment by MartinNowak** [comment]
> Why install DSFMLC to a separate directory instead of the default? Is it better to do that and export the paths? 

So you don't need run and can run on docker.

> Is Travis CI going to freak out if it never finishes?

There is a timelimit of 1h, but we need to get rid of interactive input.

**Comment by MartinNowak** [comment]
Maybe you should take over the PR, I'm not sure about the namings of the libs.

**Comment by Jebbs** [comment]
>> Why install DSFMLC to a separate directory instead of the default? Is it better to do that and export the paths? 

>So you don't need run and can run on docker.

I'm confused. So I don't need run?  (you're probably just more familiar with Travis CI than I am)

>we need to get rid of interactive input

Absolutely. I think I'm going to take a break from this project for a bit and work on a key/mouse event simulator for automating all tests.

>Maybe you should take over the PR, I'm not sure about the namings of the libs.

As far as naming goes, all you would need to do is remove the dash and everything should work (DSFML-C -> DSFMLC)

I also have no problem taking this over if you'd like.

**Comment by Jebbs** [comment]
Going to close this for now as most of what you did was absorbed into my recent work getting the library to build on OS X as well. Thanks for doing this PR, though. I finally got what you were trying to do and docker is now good to go. If you're interested you can check it out [here](https://github.com/Jebbs/DSFML/blob/18456680cb4b8608bfe3602cb7374836e634b771/.travis.yml).

Test still need to be automated though.
#198

**Pull request closed without merging**
