### PR TITLE
Adding const qualifier to appropriate methods

### PR DESCRIPTION
**Pull request by KoczurekK**
**[WIP]**
I've yet to take a look at `audio`, `network`, `system` and `window` modules, but `graphics` seems to be done.

### CODE REVIEW

**Comment by KoczurekK** [comment]
[One travis-ci test](https://travis-ci.org/Jebbs/DSFML/jobs/419179974) failed, but it looks like it's for reasons unrelated to DSFML code.

**Comment by KoczurekK** [comment]
Seems alright and tests aren't complaining (yet). Care to take a look, @Jebbs?

**Comment by Jebbs** [comment]
Looks great, thanks!

If you update the PR description, I'd be happy to merge.

**Comment by KoczurekK** [comment]
I'm not entirely sure what exactly I'm meant to update, and [CONTRIBUTING.md](https://github.com/Jebbs/DSFML/blob/master/CONTRIBUTING.md) doesn't really help. Could you elaborate?

**Comment by Jebbs** [comment]
Ah, never mind. I was talking about the description text for your pull request since I thought that it was included in the merge commit, but I don't know where I got that from....

**Comment by Jebbs** [comment]
Thank you for this, by the way!

**Pull request merged**
