### PR TITLE
EditorConfig custom format feature

### PR DESCRIPTION
**Pull request by LucienPe**
This feature allow to use [editorconfig](http://editorconfig.org/).
With this plugin we wouldn't have any buggy files anymore like this [one](https://github.com/Jebbs/DSFML/blob/2.3/appveyor.yml).

### CODE REVIEW

**Comment by Jebbs** [comment]
You call it a buggy file, but it looks like I should just use UNIX style line endings for all the files.

**Comment by LucienPe** [comment]
Right. I called it like that because in Github we see a "^M" at the end of the file.
I think it's better to use only LF, but do whatever you want.

**Comment by Jebbs** [comment]
If you rebase against the current 2.4 branch, I'll pull this in.

Alternatively, I can put a copy of your file in myself since it's been so long.

**Comment by LucienPe** [comment]
Done.
Check pull #254.

**Pull request closed without merging**
